name: CI

on:
  push:
    branches:
      - master
      - next
      - 'release-*'
      - 'v*'
  pull_request: {}
  schedule:
    - cron: '0 3 * * *' # daily, at 3am

jobs:
  install_dependencies:
    name: 'Install Dependencies'
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v3
      - uses: NullVoxPopuli/action-setup-pnpm@v2

  lint:
    name: Linting
    runs-on: ubuntu-latest
    needs: ['install_dependencies']
    timeout-minutes: 10

    steps:
      - uses: NullVoxPopuli/action-setup-pnpm@v2
      - run: pnpm lint

  test-chrome:
    name: Chrome
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/puppeteer/puppeteer:latest
    needs: ['install_dependencies']
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v1
      - uses: NullVoxPopuli/action-setup-pnpm@v2
      - run: pnpm test

  test-node:
    name: Node
    runs-on: ubuntu-latest
    needs: ['install_dependencies']
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - uses: NullVoxPopuli/action-setup-pnpm@v2
      - run: pnpm test

  test-browserstack:
    name: Browserstack
    runs-on: ubuntu-latest
    needs: ['install_dependencies']
    timeout-minutes: 20

    env:
      BROWSERSTACK_USERNAME: glimmervm1
      BROWSERSTACK_ACCESS_KEY: 7DFjbGLxYRsXWmc8tzeh

    steps:
      - uses: actions/checkout@v3
      - uses: NullVoxPopuli/action-setup-pnpm@v2
      - run: pnpm browserstack:connect
      - run: pnpm test:browserstack
      - run: pnpm browserstack:results
      - run: pnpm browserstack:disconnect

  test-types:
    name: Types
    runs-on: ubuntu-latest
    needs: ['install_dependencies']
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - uses: NullVoxPopuli/action-setup-pnpm@v2
      - run: pnpm build
      - run: pnpm test:types

  floating-dependencies:
    name: Floating Dependencies
    runs-on: ubuntu-latest
    needs: ['install_dependencies']
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - uses: NullVoxPopuli/action-setup-pnpm@v2
        with:
          args: '--no-lockfile'
      - run: pnpm test
