name: PerformanceCheck

on:
  pull_request:
    branches:
      - master

env:
  TEMP_DIR: ''

jobs:
  master-krausest-comparison:
    strategy:
      fail-fast: false
    name: Glimmer Krausest Benchmark
    runs-on: ubuntu-latest
    steps:
      - run: echo "TEMP_DIR=$(mktemp -d)" >> $GITHUB_ENV
      - run: echo ${{env.TEMP_DIR}}
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: NullVoxPopuli/action-setup-pnpm@v2
      - name: Build Experiment
        run: |
          git checkout ${{ github.sha }}
          pnpm install --frozen-lockfile
          pnpm build
      - name: Build Control
        run: |
          cd ${{env.TEMP_DIR}}
          git clone ${{github.workspace}} ${{env.TEMP_DIR}}
          cd ${{env.TEMP_DIR}}
          git checkout ${{ github.event.pull_request.base.sha }}
          pnpm install --frozen-lockfile
          pnpm build
      - name: Run Analysis
        timeout-minutes: 10
        uses: tracerbench/tracerbench-compare-action@master
        with:
          build-control: false
          build-experiment: false
          control-serve-command: pnpm --dir ${{env.TEMP_DIR}} benchmark:start --port 5173 --host
          experiment-serve-command: pnpm --dir ${{github.workspace}} benchmark:start --port 5174 --host
          control-url: http://localhost:5173/krausest
          experiment-url: http://localhost:5174/krausest
          regression-threshold: 25
          fidelity: high
          markers: 'navigationStart,renderStart,renderEnd'
          clean-after-analyze: false
      # - name: Upload Tracerbench Artifacts
      #   if: failure() || success()
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: Trace Artifacts
      #     path: tracerbench-results
