name: Bundle Size

on:
  push:
    branches: [master]
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  bundle-size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: NullVoxPopuli/action-setup-pnpm@v2.1.0
      - name: Production Build
        run: pnpm build:production
      - name: Run BundleMon
        run: pnpm bundlemon
